packages:
    - "apps/*"
    - "packages/*"

catalog:
    "pg": 8.18.0
    "zod": 4.3.6
    "jose": 6.1.3
    "dotenv": 17.2.4
    "fastify": 5.7.4
    "globals": ^16.0.0
    "jest": ^30.0.0
    "prettier": ^3.4.2
    "tsyringe": ^4.10.0
    "class-validator": ^0.14.3
    "class-transformer": ^0.5.1
    "reflect-metadata": ^0.2.2
    "source-map-support": ^0.5.21
    "drizzle-orm": ^0.45.1
    "drizzle-kit": ^0.31.9
    "date-fns": ^4.1.0
    "typescript": ^5.9.3
    "mocha": ^11.7.5
    "rxjs": ^7.8.2
    "ts-jest": ^29.2.5
    "ts-loader": ^9.5.2
    "ts-node": ^10.9.2
    "tsconfig-paths": ^4.2.0
    "supertest": ~7.1.4
    "supervisor": ~0.12.0
    "eslint": ~8.48.0
    "copy": ~0.3.2
    "concurrently": ~9.1.2
    "sqlite3": 5.1.7

catalogs:
    types:
        "@types/pg": 8.16.0
        "@types/node": 25.2.3
        "@types/mocha": 10.0.10
        "@types/jest": ^30.0.0
        "@types/supertest": ^6.0.2
        "@types/express": ^5.0.6
    foalts:
        "@foal/core": ^5.0.0
        "@foal/cli": ^5.0.0
    nestjs:
        "@nestjs/common": ^11.1.14
        "@nestjs/core": ^11.1.14
        "@nestjs/config": ^4.0.3
        "@nestjs/platform-express": ^11.1.14
        "@nestjs/platform-fastify": ^11.1.14
        "@nestjs/cli": ^11.0.16
        "@nestjs/testing": ^11.1.14
        "@nestjs/swagger": ^11.2.6
        "@nestjs/schematics": ^11.0.9
        "nestjs-i18n": ^10.6.0
    fastify:
        "@fastify/helmet": ^13.0.2
        "@fastify/compress": ^8.3.1
        "@fastify/static": ^9.0.0
    eslint:
        "@eslint/eslintrc": ^3.2.0
        "@eslint/js": ^9.18.0
        "@typescript-eslint/eslint-plugin": ^6.5.0
        "@typescript-eslint/parser": ^6.5.0
        "eslint": ^9.18.0
        "eslint-config-prettier": ^10.0.1
        "eslint-plugin-prettier": ^5.2.2
        "typescript-eslint": ^8.20.0