packages:
    - "apps/*"
    - "packages/*"

catalog:
    "pg": 8.18.0
    "zod": 4.3.6
    "jose": 6.1.3
    "dotenv": 17.2.4
    "fastify": 5.7.4
    "tsyringe": 4.10.0
    "reflect-metadata": 0.2.2
    "drizzle-orm": 0.45.1
    "drizzle-kit": 0.31.9
    "date-fns": 4.1.0
    "typescript": 5.9.3
    "@types/pg": 8.16.0
    "@types/node": 25.2.3
