export const ROLE_UNIT_OF_WORK = Symbol('ROLE_UNIT_OF_WORK');
export const CREATE_ROLE_COMMAND_HANDLER = Symbol('CREATE_ROLE_COMMAND_HANDLER');
export const UPDATE_ROLE_COMMAND_HANDLER = Symbol('UPDATE_ROLE_COMMAND_HANDLER');
export const ADD_PERMISSION_TO_ROLE_COMMAND_HANDLER = Symbol(
    'ADD_PERMISSION_TO_ROLE_COMMAND_HANDLER',
);
