export * from 'vm/address/infrastructure/persistence/drizzle/addresses.table';
export * from 'vm/geolocation/infrastructure/persistence/drizzle/geolocations.table';
export * from 'vm/offer/infrastructure/persistence/drizzle/offers.table';
export * from 'vm/offer-image/infrastructure/persistence/drizzle/offer-images.table';
export * from 'vm/offer-option-group/infrastructure/persistence/drizzle/offer-option-groups.table';
export * from 'vm/option/infrastructure/persistence/drizzle/options.table';
export * from 'vm/option-group/infrastructure/persistence/drizzle/option-groups.table';
export * from 'vm/shop/infrastructure/persistence/drizzle/shops.table';
export * from 'vm/shop-offer/infrastructure/persistence/drizzle/shop-offers.table';
