export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const ACCOUNT_QUERY_REPOSITORY = Symbol('ACCOUNT_QUERY_REPOSITORY');
export const ACCOUNT_UNIT_OF_WORK = Symbol('ACCOUNT_UNIT_OF_WORK');
