export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_QUERY_REPOSITORY = Symbol('USER_QUERY_REPOSITORY');
export const GET_USER_BY_EMAIl_QUERY_HANDLER = Symbol('GET_USER_BY_EMAIl_QUERY_HANDLER');
export const CREATE_USER_COMMAND_HANDLER = Symbol('CREATE_USER_COMMAND_HANDLER');
export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const CREATE_ACCOUNT_COMMAND_HANDLER = Symbol('CREATE_ACCOUNT_COMMAND_HANDLER');
