export const COMMENT_REPOSITORY = Symbol('COMMENT_REPOSITORY');
export const COMMENT_UNIT_OF_WORK = Symbol('COMMENT_UNIT_OF_WORK');
export const COMMENTATE_ON_COMMAND_HANDLER = Symbol('COMMENTATE_ON_COMMAND_HANDLER');
export const COMMENT_TARGET_EXISTENCE_CHECKER = Symbol('COMMENT_TARGET_EXISTENCE_CHECKER');
