export const REACTION_REPOSITORY = Symbol('REACTION_REPOSITORY');
export const REACTION_UNIT_OF_WORK = Symbol('REACTION_UNIT_OF_WORK');
export const LIKE_COMMAND_HANDLER = Symbol('LIKE_COMMAND_HANDLER');
