export const SHOP_UNIT_OF_WORK = Symbol('SHOP_UNIT_OF_WORK');
export const SHOP_REPOSITORY = Symbol('SHOP_REPOSITORY');
export const SHOP_QUERY_REPOSITORY = Symbol('SHOP_QUERY_REPOSITORY');
export const GET_SHOP_BY_SLUG_QUERY_HANDLER = Symbol('GET_SHOP_BY_SLUG_QUERY_HANDLER');
export const GET_SHOPS_BY_WORKSPACE_QUERY_HANDLER = Symbol('GET_SHOPS_BY_WORKSPACE_QUERY_HANDLER');
export const CREATE_SHOP_COMMAND_HANDLER = Symbol('CREATE_SHOP_COMMAND_HANDLER');
