export const USER_UNIT_OF_WORK = Symbol('USER_UNIT_OF_WORK');
export const WORKSPACE_UNIT_OF_WORK = Symbol('WORKSPACE_UNIT_OF_WORK');
export const GET_USER_BY_ID_QUERY_HANDLER = Symbol('GET_USER_BY_ID_QUERY_HANDLER');
export const GET_USER_INFO_BY_ID_QUERY_HANDLER = Symbol('GET_USER_INFO_BY_ID_QUERY_HANDLER');
export const ADD_ROLE_TO_USER_COMMAND_HANDLER = Symbol('ADD_ROLE_TO_USER_COMMAND_HANDLER');
export const GET_WORKSPACES_BY_OWNER_ID_QUERY_HANDLER = Symbol(
    'GET_WORKSPACES_BY_OWNER_ID_QUERY_HANDLER',
);
