export const CATEGORY_UNIT_OF_WORK = Symbol('CATEGORY_UNIT_OF_WORK');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const CATEGORY_QUERY_REPOSITORY = Symbol('CATEGORY_QUERY_REPOSITORY');
export const GET_CATEGORY_BY_ID_QUERY_HANDLER = Symbol('GET_CATEGORY_BY_ID_QUERY_HANDLER');
export const GET_CATEGORY_BY_SLUG_QUERY_HANDLER = Symbol('GET_CATEGORY_BY_SLUG_QUERY_HANDLER');
export const GET_CATEGORIES_BY_WORKSPACE_ID_QUERY_HANDLER = Symbol(
    'GET_CATEGORIES_BY_WORKSPACE_ID_QUERY_HANDLER',
);
export const CREATE_CATEGORY_COMMAND_HANDLER = Symbol('CREATE_CATEGORY_COMMAND_HANDLER');
