export const OFFER_REPOSITORY = Symbol('OFFER_REPOSITORY');
export const OFFER_QUERY_REPOSITORY = Symbol('OFFER_QUERY_REPOSITORY');
export const CREATE_OFFER_COMMAND_HANDLER = Symbol('CREATE_OFFER_COMMAND_HANDLER');
export const GET_OFFERS_BY_SHOP_QUERY_HANDLER = Symbol('GET_OFFERS_BY_SHOP_QUERY_HANDLER');
export const GET_OFFERS_BY_WORKSPACE_QUERY_HANDLER = Symbol(
    'GET_OFFERS_BY_WORKSPACE_QUERY_HANDLER',
);
