export const WORKSPACE_MEMBER_UNIT_OF_WORK = Symbol('WORKSPACE_MEMBER_UNIT_OF_WORK');
export const WORKSPACE_MEMBER_REPOSITORY = Symbol('WORKSPACE_MEMBER_REPOSITORY');
export const WORKSPACE_MEMBER_QUERY_REPOSITORY = Symbol('WORKSPACE_MEMBER_QUERY_REPOSITORY');
export const ADD_MEMBER_TO_WORKSPACE_COMMAND_HANDLER = Symbol('ADD_MEMBER_TO_WORKSPACE_COMMAND_HANDLER');