export const CUSTOMIZATION_UNIT_OF_WORK = Symbol('CUSTOMIZATION_UNIT_OF_WORK');
export const CUSTOMIZATION_COLOR_UNIT_OF_WORK = Symbol('CUSTOMIZATION_COLOR_UNIT_OF_WORK');
export const CUSTOMIZATION_REPOSITORY = Symbol('CUSTOMIZATION_REPOSITORY');
export const CUSTOMIZATION_QUERY_REPOSITORY = Symbol('CUSTOMIZATION_QUERY_REPOSITORY');
export const CUSTOMIZATION_COLOR_REPOSITORY = Symbol('CUSTOMIZATION_COLOR_REPOSITORY');
export const GET_CUSTOMIZATION_BY_ID_QUERY_HANDLER = Symbol(
    'GET_CUSTOMIZATION_BY_ID_QUERY_HANDLER',
);
export const GET_CUSTOMIZATION_BY_WORKSPACE_QUERY_HANDLER = Symbol(
    'GET_CUSTOMIZATION_BY_WORKSPACE_QUERY_HANDLER',
);
export const CREATE_CUSTOMIZATION_COMMAND_HANDLER = Symbol('CREATE_CUSTOMIZATION_COMMAND_HANDLER');
export const CREATE_CUSTOMIZATION_COLOR_COMMAND_HANDLER = Symbol(
    'CREATE_CUSTOMIZATION_COLOR_COMMAND_HANDLER',
);
