export const CUSTOMIZATION_REPOSITORY = Symbol('CUSTOMIZATION_REPOSITORY');
export const CUSTOMIZATION_QUERY_REPOSITORY = Symbol('CUSTOMIZATION_QUERY_REPOSITORY');
export const GET_CUSTOMIZATION_BY_WORKSPACE_QUERY_HANDLER = Symbol(
    'GET_CUSTOMIZATION_BY_WORKSPACE_QUERY_HANDLER',
);
