export const WORKSPACE_REPOSITORY = Symbol('WORKSPACE_REPOSITORY');
export const WORKSPACE_QUERY_REPOSITORY = Symbol('WORKSPACE_QUERY_REPOSITORY');
export const GET_WORKSPACES_QUERY_HANDLER = Symbol('GET_WORKSPACES_QUERY_HANDLER');
export const GET_WORKSPACE_BY_ID_QUERY_HANDLER = Symbol('GET_WORKSPACE_BY_ID_QUERY_HANDLER');
export const CREATE_WORKSPACE_COMMAND_HANDLER = Symbol('CREATE_WORKSPACE_COMMAND_HANDLER');
export const UPDATE_WORKSPACE_COMMAND_HANDLER = Symbol('UPDATE_WORKSPACE_COMMAND_HANDLER');
