export const SEGMENT_REPOSITORY = Symbol('SEGMENT_REPOSITORY');
export const CREATE_SEGMENT_COMMAND_HANDLER = Symbol('CREATE_SEGMENT_COMMAND_HANDLER');

export const SEGMENT_QUERY_REPOSITORY = Symbol('SEGMENT_QUERY_REPOSITORY');
export const GET_SEGMENTS_BY_CRITERIA_QUERY_HANDLER = Symbol(
    'GET_SEGMENTS_BY_CRITERIA_QUERY_HANDLER',
);
